### ISSUE TITLE
出现TypeError: UNet() got an unexpected keyword argument 'groups'

### ISSUE THREAD

**Issue by Heroism502** [yanx27/JS3C-Net#11]
请问测试的时候跑，python test_kitti_segment.py --log_dir JS3C-Net-kitti --gpu 0 --dataset test_data出现如下问题如何解。

![image](https://user-images.githubusercontent.com/22213368/128872024-0427726d-b1af-48a3-9b91-a45078521ef3.png)

**Comment by yanx27** [comment]
just set groups=1

**Comment by Heroism502** [comment]
已经设置了，还是不对，配置文件里面也设置了。
![image](https://user-images.githubusercontent.com/22213368/128872953-5301e071-f65b-4114-bb60-313622128f02.png)

![image](https://user-images.githubusercontent.com/22213368/128872895-0ffbd779-4ac9-4701-a563-0ecece447fff.png)

**Comment by Heroism502** [comment]
![image](https://user-images.githubusercontent.com/22213368/128873105-929b46b7-0e35-4ec1-b499-e5a0702bf6d0.png)

**Comment by yanx27** [comment]
![image](https://user-images.githubusercontent.com/35829331/128873773-8048a0b9-5cb8-4336-807e-48c7175a1d91.png)
delete this line

**Comment by Heroism502** [comment]
这个是我测试这一个groups值有没有读到的，不影响的，我删掉也报错了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yanx27/JS3C-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月10日(星期二) 晚上9:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yanx27/JS3C-Net] 出现TypeError: UNet() got an unexpected keyword argument 'groups' (#11)





 

 delete this line
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yanx27** [comment]
delete `group=1`

**Comment by Heroism502** [comment]
再请教下这个用你的模型测试，这个模型路径和名字要怎么改，谢谢







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yanx27/JS3C-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月10日(星期二) 晚上9:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yanx27/JS3C-Net] 出现TypeError: UNet() got an unexpected keyword argument 'groups' (#11)





 
delete group=1
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Heroism502** [comment]
请问我要测试自己的数据，比如单个bin文件，不是sequence/00-21里面的测试集和验证集，需要怎么修改，直接写一个这种sequence文件吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "735944309"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月10日(星期二) 晚上9:30
***@***.***&gt;;

主题:&nbsp;回复： [yanx27/JS3C-Net] 出现TypeError: UNet() got an unexpected keyword argument 'groups' (#11)



再请教下这个用你的模型测试，这个模型路径和名字要怎么改，谢谢







------------------ 原始邮件 ------------------
发件人:                                                                                                                        "yanx27/JS3C-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月10日(星期二) 晚上9:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yanx27/JS3C-Net] 出现TypeError: UNet() got an unexpected keyword argument 'groups' (#11)





 
delete group=1
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yanx27** [comment]
@xieliang11111 只有确保数据格式是一样的，模型可以不用改

**Comment by Heroism502** [comment]
1、请教下测试集测试的时候，模型路径在哪里设置，就是用如下命令，在test_kitti_segment.py没找到加载模型推理的函数（torch.load），
python test_kitti_segment.py --log_dir JS3C-Net-kitti --gpu 0 --dataset [val/test]
就是在哪里加载这个模型：model_segiou_0.6327_compltiou_0.2350_epoch79.pth

2、我这边推理出来的结果基本没有分割出来，应该是没推理出结果，如下所示
![image](https://user-images.githubusercontent.com/22213368/129037004-37a3b265-00a5-4ba4-8bd6-5d6db0de93a7.png)
但是对应的label有的值确有变化。
![image](https://user-images.githubusercontent.com/22213368/129037201-277fe30f-032a-4c85-ae51-66dcc816ad7b.png)
