### ISSUE TITLE
KITTI test 

### ISSUE THREAD

**Issue by Feynben** [yanx27/JS3C-Net#12]
Hi~

May I ask the voxels used in test for SSC need to be generated with the labels predicted by the segmentation?

**Comment by yanx27** [comment]
Yes, we map the predicted labels from segmentation to the original SSC inputs.

**Comment by Feynben** [comment]
Thank you for your patient reply!

**Comment by Feynben** [comment]
When I use ./gen_data to generate voxels with setting.cfg, "unknown parameter: future scans" appears. How can I correctly utilize the future scans to produce voxels? Thank you !

**Comment by Feynben** [comment]
Solved. It should be "past scans".
