### ISSUE TITLE
Number of Segmentation model block_reps

### ISSUE THREAD

**Issue by min2209** [yanx27/JS3C-Net#13]
Hi, 

great work. I've been trying to reproduce the segmentation results in your paper. However, I noticed something strange - in the checkpoint you released, there are enough weights for the segmentation module (starting with `seg_head.sparseModel`) for there to be 2 segmentation `block_reps`, but in all your .yaml configurations and `log/args.txt` it is specified that `Segmentation: block_reps` should equal 1. Could you clarify?

Thanks!

**Comment by yanx27** [comment]
Hi, `block_reps` just slightly affect the performance, you can just use 1 to speed up the training.
