### ISSUE TITLE
 Why do you need to generate semantic scene completion targets through multi-frame merging？

### ISSUE THREAD

**Issue by jialeli1** [yanx27/JS3C-Net#14]
I noticed that semanticKITTI provides GT for semantic scene completion, so why do you need to generate semantic scene completion targets through multi-frame merging? Is there any difference between them?

Thanks.

**Comment by yanx27** [comment]
Hi, Semantickitti only provided the completion GT every five frames when we submitted the paper. There is not any difference between them.
