### ISSUE TITLE
JS3C_default_spconv.yaml vs JS3C_default_kitti.yaml

### ISSUE THREAD

**Issue by zoomin-lee** [yanx27/JS3C-Net#18]
Hi, authors.
Thank you for your great work and sharing the code.

I have a question about the difference between the two yaml files.
JS3C_default_spconv.yaml uses segmentation model as spconv,
but JS3C_default_kitti.yaml uses segmentation model as scn.
I think spconv is a simple and fast version of scn. 
so, are those two yaml files the same?

Thanks.

**Comment by yanx27** [comment]
Thanks for your attention @zoomin-lee . Our experimental results are obtained via `JS3C_default_kitti.yaml`, and the another config file `JS3C_default_spconv.yaml` is only used for providing another choice to the users, which is not checked the performance carefully.
