### ISSUE TITLE
Semantic Scene Completion GT

### ISSUE THREAD

**Issue by superxiaoying** [yanx27/JS3C-Net#4]
Hi, 

Thanks for your great work.

I want to know that the SSC GT label "data_odometry_voxels_all.zip" is from the semantic-kitti official or you prepared it ?
http://semantic-kitti.org/assets/data_odometry_voxels_all.zip

Best,
Ying

**Comment by yanx27** [comment]
@superxiaoying Hi, thanks for your attention. We use official SSC GT from semantickitti while use mannually generated GT for semanticposs dataset.

**Comment by superxiaoying** [comment]
@yanx27 Thx. I think there maybe a little unfair for SSC task, since the number of training samples for standard SSC is about 1/5 of the all. The reported performance of JS3CNet paper uses all data, right? Have you tried less training samples and how much influence will it cause?

Best,
Ying

**Comment by yanx27** [comment]
Yes, we used 1/5 data  for training of SSC, and it can achieve similar results. I think this because of the redundancy of LiDAR sequences.

**Comment by superxiaoying** [comment]
Thanks for your response.
