### ISSUE TITLE
Multi frames fusion

### ISSUE THREAD

**Issue by superxiaoying** [yanx27/JS3C-Net#5]
Hi, @yanx27 

Thanks for your great work.

I want know how you fuse multi-frames, just as shown by your fig1. Could you please share the fusion/ multi frames transformation code?
![image](https://user-images.githubusercontent.com/17792319/106577197-09839a80-6579-11eb-9e44-0774f8315602.png)

Best,
Ying

**Comment by yanx27** [comment]
Hi, we used [voxelizer](https://github.com/jbehley/voxelizer) to generate our dense scene.
