### ISSUE TITLE
voxels

### ISSUE THREAD

**Issue by libozan** [yanx27/JS3C-Net#6]
@yanx27 Thank you for sharing your code. But I have a problem and need your help.I have downloaded the pre-processed SemanticPOSS SSC labels according to your tips.But the following error message appeared

Voxel directory missing: .../JS3C-Net-main/data/semantic_kitti/dataset/sequences/06/voxels

There is only the voxelization tag of sequence 00-05 in the pre-processed file. Do I need to voxelize all the data?

**Comment by Gao-JT** [comment]
@libozan Hello, Thanks for your interest in our work.  I found that the dataset you used (.../JS3C-Net-main/data/**semantic_kitti**/dataset/sequences/06/voxels) is SemanticKITTI, not SemanticPOSS. Therefore, I think the reason for this error may be that:
1. You used **the wrong yaml file** 
2. **The dataset path in the yaml file** is specified **incorrectly**.
**Please check the yaml file you used and the dataset path in the yaml file**. Note that, **if you are using the pre-processed Semantic-POSS SSC labels provided by our zipped file,** please change **'voxels_align'** in poss_dataset.py (https://github.com/yanx27/JS3C-Net/blob/c4eed02b2febc118b31c074a9f1d6321ad1c04be/poss_dataset.py#L67  ; https://github.com/yanx27/JS3C-Net/blob/c4eed02b2febc118b31c074a9f1d6321ad1c04be/poss_dataset.py#L149 ; https://github.com/yanx27/JS3C-Net/blob/c4eed02b2febc118b31c074a9f1d6321ad1c04be/poss_dataset.py#L150 to **'voxels'** or change the name of the **'voxels '** folder in the downloaded unzipped file to **'voxels_align'**

**Comment by libozan** [comment]
@yanx27 thank you for your help.I think there may be a problem with my data set storage path, I put semantic_kitti and semantic_poss under the same 00 file.

I found that the train data in kitti_dataset contains the following types of files
> SPLIT_FILES = {
    "train": [".bin", ".label", ".invalid", ".occluded"]

My data set format is as follows
SemanticKITTI
├── dataset
│   ├── sequences
│   │  ├── 00
│   │  │  ├── labels
│   │  │  ├── velodyne
│   │  │  ├── cailb\poses\times
│   │  ├── 01
I don’t know if I am missing some data.Thank you very much for your answers！

**Comment by yanx27** [comment]
@libozan Hi, did you successfully download SemanticKITTI SSC data, which is mentioned in README?
![image](https://user-images.githubusercontent.com/35829331/113386235-62768000-93bc-11eb-9c28-e596411f7487.png)

**Comment by libozan** [comment]
@yanx27 Thank you very much for your answers, I think I understood it wrong at the time. I used the standard data set downloaded from the semantickitti official website and the semanticposs preprocessed data you provided, but I didn’t use the SemanticKITTI SSC data you mentioned above.

**Comment by yanx27** [comment]
Ok, thanks for your attention again.
