### ISSUE TITLE
train time

### ISSUE THREAD

**Issue by libozan** [yanx27/JS3C-Net#7]
@yanx27      I chose to retrain a network model, but each epoch takes too long and requires more than 10 hours of training.
 
![Screenshot from 2021-04-06 18-36-41](https://user-images.githubusercontent.com/59766249/113699512-3cc4e000-9708-11eb-8a45-a6ceec8dcec9.png)
batch size=1   GPU=2080     `python train.py  --config opt/JS3C_default_kitti.yaml`
I want you to confirm if there is a problem with my training.Thank you for your help.

**Comment by yanx27** [comment]
@libozan Hi, training with batchsize=1 may loss the acceleration of  parallel computing. Using larger batch size can speed up :)

**Comment by libozan** [comment]
Thanks for your answer.
